# -*- coding: utf-8 -*-
"""internship 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d0qDiwisV2QjP9mcABA2OTPBE0fpJPFD
"""

import pandas as p
import numpy as np

d=p.read_csv("movies.csv")
d.head
print(d.isnull())

d.head(6)

d.sample(6)

d.isnull().sum()
a=d.isnull()

d.dropna()

# how many total missing values do we have?
total = np.product(d.shape)
t_missing= a.sum()

# percent of data that is missing
(t_missing/total) * 100

d.fillna(method = 'bfill', axis=0).fillna(0)

from matplotlib import pyplot as plt
_df_1['total_gross'].plot(kind='hist', bins=20, title='total_gross')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_3.groupby('movie_title').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['genre'].value_counts()
    for x_label, grp in _df_17.groupby('release_date')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('release_date')
_ = plt.ylabel('genre')

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='index', y='total_gross', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_11['inflation_adjusted_gross'].plot(kind='line', figsize=(8, 4), title='inflation_adjusted_gross')
plt.gca().spines[['top', 'right']].set_visible(False)